export const productData = {
  camaras: [
    {
      name: "Cámara Domo FullHD ColorV U con AUDIO",
      brand: "Hikvision",
      description: "Domo interior con audio, alta durabilidad",
      resolution: "2 MP, lente fija 2.8 mm o 3.6 mm",
      features: [
        "ColorVu 24/7",
        "3D DNR",
        "Audio coaxial/micrófono",
        "Visión nocturna 20 m",
        "TVI/AHD/CVI/CVBS",
      ],
      image: "image/camera/1.jpg",
    },
    {
      name: "4 MP Smart Hybrid Light Fixed Bullet Network Camera",
      brand: "Hikvision",
      description: "Bala fija IP con luz híbrida",
      resolution: "4 MP (2560×1440 px)",
      features: [
        "Detección IA (personas/vehículos)",
        "Micrófono",
        "IP67",
        "H.265+",
        "Slot MicroSD (512 GB)",
      ],
      image: "image/camera/2.png",
    },
    {
      name: "Cámara domo EYEBALL FULL COLOR 2 MP 2.8 mm",
      brand: "Hikvision",
      description: "Domo interior con visión a color 24/7",
      resolution: "2 MP, lentes 2.8/3.6/6 mm",
      features: [
        "ColorVu",
        "3D DNR",
        "Visión nocturna 20 m",
        "TVI/AHD/CVI/CVBS",
      ],
      image: "image/camera/3.png",
    },
    {
      name: "Cámara tubo IR bullet 1 MP P 2.8 mm",
      brand: "Hikvision",
      description: "Bala analógica para exteriores",
      resolution: "2 MP, lente varifocal 2.7–12 mm",
      features: ["IR nocturno hasta 60 m", "IP67", "Varifocal motorizado"],
      image: "image/camera/4.png",
    },
    {
      name: "Cámara de seguridad inteligente para exteriores H9c Dual",
      brand: "Ezviz",
      description: "PT 360° Wi‑Fi con seguimiento IA",
      resolution: "Dual 2K (2304×1296 px)",
      features: [
        "Cobertura 360°",
        "Detección IA",
        "Seguimiento",
        "Sirena",
        "Luz estroboscópica",
        "Micro‑SD y cloud",
      ],
      image: "image/camera/5.png",
    },
    {
      name: "Cámara de red Hikvision EXIR Fixed Mini Bullet 2 MP H.265+",
      brand: "Hikvision",
      description: "Bala IP compacta exterior",
      resolution: "2 MP, lente fija 2.8 mm",
      features: [
        "IR 30 m",
        "IP67",
        "PoE",
        "Compresión H.265+",
        "DWDR, BLC, 3D DNR",
      ],
      image: "image/camera/6.png",
    },
    {
      name: "Cámara bala IP ColorVu MD 2.0 AcuSense HD+ 6 Mpx 2.8 mm WDR 120 dB",
      brand: "Hikvision",
      description: "Bala IP 6 MP con IA y visión nocturna a color",
      resolution: "6 MP, lente 2.8 mm",
      features: [
        "ColorVu",
        "WDR 120 dB",
        "Detección IA",
        "IP67",
        "H.265+",
        "iVMS/Hik‑Connect",
      ],
      image: "image/camera/7.png",
    },
  ],
  switches: [
    {
      name: "Switch sobremesa 8 puertos 10/100/1000 Mbps",
      brand: "TP‑Link",
      description: "Switch Gigabit para hogar/oficina",
      ports: "8 × RJ45",
      features: ["QoS", "Metal", "MDI/MDIX", "Plug & Play"],
       image: "image/switch/1.png",
    },
    {
      name: "Conmutador Gigabit no gestionado 5 puertos",
      brand: "Genérico",
      description: "Switch de escritorio sin ventilador",
      ports: "5 × RJ45 Gigabit",
      features: ["Carcasa metálica", "IEEE 802.3/802.3u/x"],
      image: "image/switch/2.png",
    },
    {
      name: "Switch TP‑Link LS1008G (8 puertos 10/100/1000 Mbps)",
      brand: "TP‑Link",
      description: "Switch Gigabit para videovigilancia",
      ports: "8 × RJ45",
      features: ["No bloqueante", "Ideal para archivos pesados"],
     image: "image/switch/3.png",
    },
    {
      name: "Switch sobremesa 5 puertos 10/100/1000 Mbps",
      brand: "Genérico",
      description: "Expansión de red con ahorro energético",
      ports: "5 × RJ45",
      features: ["Auto‑Neg", "Auto‑MDI/MDIX", "Green Ethernet"],
      image: "image/switch/4.png",
    },
  ],
  routers: [
    {
      name: "Router Mercusys Rompe Muro 3 Antenas MW330HP 7 dBi",
      brand: "Mercusys",
      description: "Router/Repetidor/WISP de largo alcance",
      speed: "300 Mbps, 2.4 GHz",
      features: ["Botón Turbo", "Chip PA", "Antenas 7 dBi"],
      image: "image/router/1.png",
    },
    {
      name: "TL‑WR840N TP‑Link Router Inalámbrico Wi‑Fi 2.4 GHz",
      brand: "TP‑Link",
      description: "Router doméstico básico",
      speed: "300 Mbps, 2.4 GHz",
      features: ["WPS", "Control ancho de banda", "WDS"],
      image: "image/router/2.png",
    },
    {
      name: "Adaptador Wifi USB 5 dBi Rompe Muro 300 Mbps MW300UH",
      brand: "Mercusys",
      description: "Adaptador de alta ganancia para PC",
      speed: "300 Mbps",
      features: ["2× antenas 5 dBi", "2×2 MIMO", "Compatible Windows"],
       image: "image/router/3.png",
    },
    {
      name: "Router inalámbrico N 2.4 GHz 300 Mbps",
      brand: "Mercusys",
      description: "Router con 3 antenas externas",
      speed: "300 Mbps, 2.4 GHz",
      features: ["4 modos", "Control parental", "Compatible IPv6/IPTV"],
       image: "image/router/4.png",
    },
    {
      name: "Access Point TP‑Link TL‑WA801N 300 Mbps",
      brand: "TP‑Link",
      description: "Punto de acceso/cliente/repetidor",
      speed: "300 Mbps, 2.4 GHz",
      features: ["WPA/WPA2", "PoE pasivo", "2 antenas"],
      image: "image/router/5.png",
    },
  ],
  alarmas: [
    {
      name: "ALARMA SMART RESIDENCIAL CONTRA ROBO Hagroy HS‑X",
      brand: "Hagroy",
      description: "Kit inteligente con integración de cámaras",
      features: [
        "8 zonas cableadas",
        "24 inalámbricas",
        "Hasta 16 usuarios/32 controles",
        "Audio disuasorio",
        "App iHagroy",
        "Central GSM/4G",
      ],
       image: "image/alarm/1.png",
    },
    {
      name: "ALARMA COMUNITARIA ALCOM MAX RED 4G LTE ALMX4G",
      brand: "Genérico",
      description: "Sistema de alarma comunitaria avanzada",
      features: [
        "Hasta 2000 usuarios y controles",
        "Sirena potente",
        "Conexión 4G/VoLTE",
        "Monitoreo web",
        "Salidas para luces/reflectores",
      ],
       image: "image/alarm/2.png",
    },
  ],
};
