 export const courses = [
    {
      id: 1,
      title: "Reaccionar Frente Para Volver",
      instructor: "Courses by",
      lessons: 12,
      students: 50,
      rating: 5,
      comments: 15,
      discount: 40,
      bgColor: "from-pink-400 to-orange-400",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 2,
      title: "PHP Principiante Avanzado",
      instructor: "Courses by",
      lessons: 12,
      students: 50,
      rating: 5,
      comments: 15,
      discount: null,
      bgColor: "from-purple-500 to-blue-500",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 3,
      title: "Cero Angular a la Maestría",
      instructor: "Courses by",
      lessons: 8,
      students: 30,
      rating: 5,
      comments: 5,
      discount: 10,
      bgColor: "from-yellow-400 to-orange-600",
      image: "/placeholder.svg?height=200&width=300",
    },
     {
      id: 4,
      title: "Reaccionar Frente Para Volver",
      instructor: "Courses by",
      lessons: 12,
      students: 50,
      rating: 5,
      comments: 15,
      discount: 40,
      bgColor: "from-pink-400 to-orange-400",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 5,
      title: "PHP Principiante Avanzado",
      instructor: "Courses by",
      lessons: 12,
      students: 50,
      rating: 5,
      comments: 15,
      discount: null,
      bgColor: "from-purple-500 to-blue-500",
      image: "/placeholder.svg?height=200&width=300",
    },
    {
      id: 6,
      title: "Cero Angular a la Maestría",
      instructor: "Courses by",
      lessons: 8,
      students: 30,
      rating: 5,
      comments: 5,
      discount: 10,
      bgColor: "from-yellow-400 to-orange-600",
      image: "/placeholder.svg?height=200&width=300",
    },
    
  ]